"use client"

import { useState } from "react"

import { MeridianResponseCurves } from "./meridian-response-curves"

export function MMMResponseCurvesPage() {
  const [confidenceLevel, setConfidenceLevel] = useState(0.9)
  const [plotSeparately, setPlotSeparately] = useState(false)
  const [includeCI, setIncludeCI] = useState(true)


  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-emerald-950/70 p-6 shadow-2xl backdrop-blur">
        <header className="pb-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div className="flex-1">
              <p className="text-xs uppercase tracking-[0.3em] text-emerald-200/70">Meridian Visualizer</p>
              <h1 className="mt-2 text-3xl font-semibold text-emerald-50">Channel response curves</h1>
              <p className="mt-2 max-w-3xl text-sm text-emerald-200/70">
                Interactive response curves generated by Meridian's built-in visualizer. Hover over curves for details,
                use the toolbar to export, and adjust settings below.
              </p>
            </div>

            <div className="flex flex-col gap-4 rounded-2xl border border-emerald-400/20 bg-emerald-900/40 p-4 text-sm sm:min-w-[260px]">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-emerald-200/70">Confidence level</span>
                  <span className="font-semibold text-emerald-50">{(confidenceLevel * 100).toFixed(0)}%</span>
                </div>
                <input
                  type="range"
                  min={0.5}
                  max={0.99}
                  step={0.05}
                  value={confidenceLevel}
                  onChange={(e) => setConfidenceLevel(Number(e.target.value))}
                  className="w-full accent-emerald-400"
                />
              </div>

              <div className="flex items-center justify-between border-t border-emerald-400/20 pt-3">
                <span className="text-emerald-200/70">Separate plots</span>
                <button
                  onClick={() => setPlotSeparately(!plotSeparately)}
                  className={`relative h-6 w-11 rounded-full transition-colors ${
                    plotSeparately ? "bg-emerald-400" : "bg-emerald-900"
                  }`}
                >
                  <span
                    className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-transform ${
                      plotSeparately ? "translate-x-6" : "translate-x-1"
                    }`}
                  />
                </button>
              </div>

              <div className="flex items-center justify-between border-t border-emerald-400/20 pt-3">
                <span className="text-emerald-200/70">Show confidence intervals</span>
                <button
                  onClick={() => setIncludeCI(!includeCI)}
                  className={`relative h-6 w-11 rounded-full transition-colors ${
                    includeCI ? "bg-emerald-400" : "bg-emerald-900"
                  }`}
                >
                  <span
                    className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-transform ${
                      includeCI ? "translate-x-6" : "translate-x-1"
                    }`}
                  />
                </button>
              </div>

              <p className="border-t border-emerald-400/20 pt-3 text-xs text-emerald-200/60">
                Charts powered by Meridian's MediaEffects visualizer
              </p>
            </div>
          </div>
        </header>

        <MeridianResponseCurves
          confidenceLevel={confidenceLevel}
          plotSeparately={plotSeparately}
          includeCI={includeCI}
        />
      </section>
    </div>
  )
}
